// Golden-master parity test (PLANNING.md Phase A2): proves the new generic
// programEngine.js, fed the transform script's output, reproduces every real
// session in the current live season exactly the same as the old ski-specific
// logic in app.js. This has to pass before any real program data migrates --
// a reindexing or option-mapping bug here would otherwise silently corrupt
// Eric's running season.
//
// The "old" implementation below is a faithful, self-contained copy of the
// relevant functions from public/app.js as of the current live program (not
// an import of app.js itself, which is a DOM-coupled IIFE with no exports).
// Keeping it self-contained also means this test can't accidentally start
// comparing the new engine against itself if app.js changes during Phase B.
//
// Both fixtures are frozen JSON, regenerated by `node scripts/transform-program.mjs
// --out test/fixtures` whenever public/program.js changes. Parsing program.js's
// JS-object-literal requires eval, which the Workers test runtime (workerd)
// disallows entirely -- so that parsing happens once, offline, via plain Node.
import { describe, expect, it } from "vitest";
import { getSession as newGetSession, sessionKeysFor } from "../public/programEngine.js";
import legacy from "./fixtures/legacy.json";
import content from "./fixtures/content.json";

function oldParseRx(rx, o) {
  const r = { sets: 1, reps: "", pct: o.pct || null };
  let m;
  if ((m = rx.match(/^(\d+)\s*×\s*(\d+)/))) {
    r.sets = +m[1];
    r.reps = m[2];
  } else if ((m = rx.match(/^(\d+)\s*×/))) {
    r.sets = +m[1];
  } else if ((m = rx.match(/(\d+)\s*rounds?/))) {
    r.sets = +m[1];
  }
  if ((m = rx.match(/@\s*([\d.]+)%/))) r.pct = +m[1] / 100;
  return r;
}

function oldSessionKeys(P, w) {
  const s = P.singles.filter((x) => x.week === w).map((x) => x.key);
  return s.length ? s : ["A", "B", "C"];
}

function oldGetSession(P, w, key) {
  const single = P.singles.find((x) => x.week === w && x.key === key);
  let raw, title, type, extra = {};
  if (single) {
    raw = single.items.map(([n, rx, o]) => [n, rx, o || {}]);
    title = single.title;
    type = single.type;
    extra = single;
  } else {
    const blk = P.blocks.find((b) => b.weeks.includes(w));
    if (!blk) return null;
    const idx = blk.weeks.indexOf(w);
    const s = blk.sessions[key];
    if (!s) return null;
    raw = s.items.map(([n, rx, o]) => [n, Array.isArray(rx) ? rx[idx] : rx, o || {}]);
    title = s.title;
    type = key;
    extra = s;
  }
  const items = raw
    .filter(([, rx]) => rx && rx !== "—")
    .map(([name, rx, o], i) => Object.assign({ i, name, rx }, o, oldParseRx(rx, o)));
  return { week: w, key, title, type, items, test: !!extra.test, me: !!extra.me, noWarmup: !!extra.noWarmup };
}

function oldWeekMeta(P, w) {
  return P.season.weeks.find((x) => x.n === w);
}

function oldNoSpikes(P, w, session) {
  return session.me || (oldWeekMeta(P, w) || {}).deload || session.type === "C";
}

// Normalize an item down to the fields that actually affect rendering, so
// this test isn't sensitive to incidental key-ordering differences between
// the two representations.
// `circuit` is deliberately NOT compared for exact equality: the old format
// used a bare `circuit: 1` flag referencing the single global meCircuit
// string; the new format replaces it with a real key reference
// (`circuit: "meCircuit"`), exactly as PLANNING.md's generalization describes.
// Presence/absence is compared here; the exact new key is checked separately.
function normalizeItem(it) {
  const { i, name, rx, sets, reps, pct, bw, u, norpe, lift, t, v, n, desc } = it;
  return { i, name, rx, sets, reps, pct: pct ?? null, bw: bw ?? null, u: u ?? null, norpe: norpe ?? null, lift: lift ?? null, t: t ?? null, v: v ?? null, n: n ?? null, hasCircuit: !!it.circuit, desc: desc ?? null };
}

describe("program.js -> content parity (Phase A2 golden master)", () => {
  const weeks = legacy.season.weeks.map((w) => w.n);

  it("produces the same session keys for every real week", () => {
    for (const w of weeks) {
      const oldKeys = oldSessionKeys(legacy, w).sort();
      const newKeys = sessionKeysFor(content, w).sort();
      expect(newKeys, `week ${w}`).toEqual(oldKeys);
    }
  });

  it("produces the same items, rx, and options for every real (week, key) session", () => {
    let compared = 0;
    for (const w of weeks) {
      for (const key of oldSessionKeys(legacy, w)) {
        const oldSession = oldGetSession(legacy, w, key);
        const newSession = newGetSession(content, w, key);
        expect(newSession, `week ${w} key ${key} should exist in the new engine`).toBeTruthy();
        expect(newSession.title, `week ${w} key ${key} title`).toBe(oldSession.title);
        expect(newSession.items.map(normalizeItem), `week ${w} key ${key} items`).toEqual(
          oldSession.items.map(normalizeItem),
        );
        compared++;
      }
    }
    expect(compared).toBeGreaterThan(0);
  });

  it("matches the old noSpikes logic (me || deload || type C) via the new noWarmupSpikes flag", () => {
    for (const w of weeks) {
      for (const key of oldSessionKeys(legacy, w)) {
        const oldSession = oldGetSession(legacy, w, key);
        const newSession = newGetSession(content, w, key);
        const expected = oldNoSpikes(legacy, w, oldSession);
        expect(newSession.noWarmupSpikes, `week ${w} key ${key} noWarmupSpikes`).toBe(expected);
      }
    }
  });

  it("matches the old test-day flag and note", () => {
    for (const w of weeks) {
      for (const key of oldSessionKeys(legacy, w)) {
        const oldSession = oldGetSession(legacy, w, key);
        const newSession = newGetSession(content, w, key);
        expect(newSession.isTest, `week ${w} key ${key} isTest`).toBe(!!oldSession.test);
        if (oldSession.test) {
          expect(newSession.testDayNote).toBe("Test day: add a second block of 3 spikes and one extra ramp set.");
        } else {
          expect(newSession.testDayNote).toBeNull();
        }
      }
    }
  });

  it("preserves every video key reference", () => {
    for (const w of weeks) {
      for (const key of oldSessionKeys(legacy, w)) {
        const oldSession = oldGetSession(legacy, w, key);
        const newSession = newGetSession(content, w, key);
        const oldVideoKeys = oldSession.items.map((it) => it.v).filter(Boolean).sort();
        const newVideoKeys = newSession.items.map((it) => it.v).filter(Boolean).sort();
        expect(newVideoKeys, `week ${w} key ${key} video keys`).toEqual(oldVideoKeys);
      }
    }
  });

  it("preserves every test key reference", () => {
    for (const w of weeks) {
      for (const key of oldSessionKeys(legacy, w)) {
        const oldSession = oldGetSession(legacy, w, key);
        const newSession = newGetSession(content, w, key);
        const oldTestKeys = oldSession.items.map((it) => it.t).filter(Boolean).sort();
        const newTestKeys = newSession.items.map((it) => it.t).filter(Boolean).sort();
        expect(newTestKeys, `week ${w} key ${key} test keys`).toEqual(oldTestKeys);
      }
    }
  });

  it("maps every old bare circuit:1 flag to the new circuit:'meCircuit' key reference", () => {
    for (const w of weeks) {
      for (const key of oldSessionKeys(legacy, w)) {
        const oldSession = oldGetSession(legacy, w, key);
        const newSession = newGetSession(content, w, key);
        oldSession.items.forEach((oldItem, i) => {
          if (oldItem.circuit) {
            expect(newSession.items[i].circuit, `week ${w} key ${key} item ${i} circuit`).toBe("meCircuit");
          } else {
            expect(newSession.items[i].circuit, `week ${w} key ${key} item ${i} circuit`).toBeFalsy();
          }
        });
      }
    }
  });
});
